config/routes.rb
CivilWarEvents::Application.routes.draw do
  devise_for :users

  resources :categories, :constraints => { :id => /[^\/]*/ } do
    shallow do
      resources :events do
        member do
          put :approve
          put :unapprove
        end
      end
    end
    match 'calendars/:year/:month', :to => 'calendars#show'
    match 'events/:year/:month/:day', :to => 'events#by_day', :as => 'events_by_day'
  end

  root :to => 'categories#index'
  match 'teach', :to => 'root#teach'
  match 'events/:year/:month/:day', :to => 'root#teach_events_by_day', :as => 'teach_events_by_day'
  match 'calendars/:year/:month', :to => 'calendars#teach'
end

app/models/event.rb
class Event < ActiveRecord::Base
  include ActionController::UrlWriter

  has_many :category_events
  has_many :categories, :through => :category_events

  scope :future, :conditions => ['events.end >= ? OR events.start >= ?', Time.now, Time.now]
  scope :approved, :conditions => { :approved => true }

  validates_presence_of :categories
  validates_presence_of :start

  attr_protected :approved

  def approve!
    self.approved = true
    save!
  end
  def unapprove!
    self.approved = false
    save!
  end

  def day
    start.httpdate
  end

  def time
    if self.end
      if start.strftime('%Y%m%d') == self.end.strftime('%Y%m%d')
        "From #{start.strftime '%I:%M%p'} to #{self.end.strftime '%I:%M%p'}"
      else
        "From #{start.strftime '%B %d, %Y'} to #{self.end.strftime '%B %d, %Y'}"
      end
    elsif all_day
      'All day'
    elsif start.present?
      start.strftime '%I:%M%p'
    else
      'No time specified'
    end
  end

  def url
    website.present? ? website : "http://seekingmichigan.org/event_manager/events/#{to_param}"
  end

  def as_json(options = {})
    {:id => id, :url => url, :name => name, :description => description, :time => time, :location => location }
  end
end

app/controllers/events_controller.rb
require 'date'
require 'time'
require 'fileutils'

class EventsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :by_day, :show, :new, :create]

  include ActionView::Helpers::TextHelper

  # GET /events
  # GET /events.xml
  def index
    respond_to do |format|
      format.html do
        load_html_events
      end
      format.xml do
        load_data_events
        render :xml => @events
      end
      format.json do
        load_data_events
        render :json => @events
      end
    end
  end

  def by_day
    day_start = DateTime.new params[:year].to_i, params[:month].to_i, params[:day].to_i, 0, 0, 0
    day_end = DateTime.new params[:year].to_i, params[:month].to_i, params[:day].to_i, 23, 59, 59
    @events = category.events.find :all, 
      :conditions => ['? <= end AND ? >= start AND approved = ?', day_start, day_end, true]
    @date = Date.new params[:year].to_i, params[:month].to_i, params[:day].to_i
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def calendar
    category
    @calendar = Event.calendar

    respond_to do |format|
      format.json { render :json => @calendar }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    load_data

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    category
    @categories = Category.order('name')
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    load_data
    @categories = Category.order('name')
  end

  # POST /events
  # POST /events.xml
  def create
    parse_dates
    @category = Category.find_by_name params[:category_id]
    # Commented out line below to prevent addition of new events
    # @event = Event.new params[:event]
    @event.approved = params[:event][:approved] if user_signed_in?
    @categories = Category.order('name')

    respond_to do |format|
      if @event.save
        clear_zend_cache
        format.html
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    parse_dates
    @event = Event.find(params[:id])
    @event.approved = params[:event][:approved]
    @category = @event.categories.first
    @categories = Category.order('name')

    respond_to do |format|
      if @event.update_attributes(params[:event])
        clear_zend_cache
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    load_data
    @event.destroy
    clear_zend_cache

    respond_to do |format|
      format.html { redirect_to(category_events_url(category)) }
      format.xml  { head :ok }
    end
  end

  def approve
    load_data
    event.approve!
    clear_zend_cache
    redirect_to(event, :notice => 'Event was approved.')
  end
  def unapprove
    load_data
    event.unapprove!
    clear_zend_cache
    redirect_to(event, :notice => 'Event was unapproved.')
  end

private
  def parse_dates
    [:start, :end].each { |t| params[:event][t] = parse_date(params[:event][t]) } if params[:event]
  end

  def parse_date(string)
    return nil if string.blank?
    d = Chronic.parse(string)
    d ||= Time.parse string
    d
  end

  def load_html_events
    @events = category.events.future 
    @events = @events.approved unless user_signed_in?
  end

  def load_data_events
    @events = category.events.future.approved
    @events = @events.limit params[:limit] if params[:limit]
    @events = @events.group_by(&:day)
    @events.each do |date, list|
      list.each do |event|
        truncation = event['description'].split(/\s/)[0..9].join(' ')
        description = truncation + '... ' + "<a href=\"#{event_url(event)}\">read more &gt;&gt;</a>"
        event['description'] = description
      end
    end
  end

  def clear_zend_cache
    # I know this is crazy, but it's 12am and I'm doing it!
    Dir.glob('/tmp/zend_cache*').each do |cache|
      FileUtils.rm cache
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_date(date)
    return '' if date.nil?

    if date.hour == 0 && date.min == 0
      date.strftime '%A, %B %d, %Y'
    else
      date.strftime '%A, %B %d, %Y %I:%M%p'
    end
  end

  def event_category_link_list(categories)
    categories.map do |category|
      link_to h(category.name), category_path(category)
    end.to_sentence.html_safe
  end
end

app/views/events/_event.html.erb
<h2><%= event.name %></h2>
<strong>an event for <%= event_category_link_list(event.categories) %></strong>

<% if event.description.present? %>
  <h3>Description:</h3>
  <p><%= event.description %></p>
<% end %>

<h3>Dates/times:</h3>
<p>
  <%= event_date event.start %>
  <% if event.end %>
    &mdash; <%= event_date event.end %>
  <% end %>
</p>

<% if event.all_day %>
  <h3>This is an all day event</h3>
<% end %>

<% if event.location.present? %>
  <h3>Location:</h3>
  <p><%= event.location %></p>
<% end %>

<% if event.website.present? %>
  <h3>Website:</h3>
  <p><%= link_to event.website, event.website %></p>
<% end %>

<% if event.submitted_by.present? %>
  <h3>Submitted by:</h3>
  <p><%= event.submitted_by %></p>
<% end %>

<% if event.phone.present? %>
  <h3>Phone:</h3>
  <p><%= event.phone %></p>
<% end %>

<% if event.email.present? %>
  <h3>Email:</h3>
  <p><%= mail_to event.email, event.email %></p>
<% end %>

<% if event.cost.present? %>
  <h3>Cost:</h3>
  <p><%= event.cost %></p>
<% end %>

<% if event.registration_url.present? %>
  <h3>Registration Link:</h3>
  <p><%= link_to event.registration_url, event.registration_url %></p>
<% end %>

<% if user_signed_in? %>
  <div class="event-buttons">
    <% if event.approved %>
      <%= link_to 'Unapprove', unapprove_event_path(event), :method => :put %>
    <% else %>
      <%= link_to 'Approve', approve_event_path(event), :method => :put %>
    <% end %>
    |
    <%= link_to 'Edit', edit_event_path(event), :method => :get %>
    |
    <%= link_to 'Delete', event_path(event), :method => :delete %>
    <% if @category %>
      |
      <%= link_to 'List', category_events_path(@category) %>
    <% end %>
  </div>
<% end %>

app/views/events/_form.html.erb
<!-- Commented out form code in Ruby -->
<%= # form_for((@event.new_record? ? [@category, @event] : @event)) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="half">
    <div class="field">
      <h3><%= f.label :name, 'Event name' %></h3>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <h3><%= f.label :description %></h3>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <h3><%= f.label :start, 'Start date/time' %></h3>
      <%= f.text_field :start, :value => @event.try(:start).try(:to_formatted_s, :long) %>
      e.g. 09/20/2010 9:00 a.m.
    </div>
    <div class="field">
      <h3><%= f.label :end, 'End date/time' %></h3>
      <%= f.text_field :end, :value => @event.try(:end).try(:to_formatted_s, :long) %>
      e.g. 09/20/2010 9:00 a.m.
    </div>
  </div>
  <div class="half">
    <div class="field">
      <h3><%= f.label :location, 'Location and address' %></h3>
      <%= f.text_area :location, :rows => 5 %>
    </div>
    <div class="field">
      <h3><%= f.label :submitted_by %></h3>
      <%= f.text_field :submitted_by %>
    </div>
    <div class="field">
      <h3><%= f.label :phone %></h3>
      <%= f.text_field :phone %>
    </div>
    <div class="field">
      <h3><%= f.label :website %></h3>
      <%= f.text_field :website %>
    </div>
    <div class="field">
      <h3><%= f.label :email %></h3>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <h3><%= f.label :cost %></h3>
      <%= f.text_field :cost %>
    </div>
    <div class="field">
      <h3><%= f.label :registration_url, 'Registration link' %></h3>
      <%= f.text_field :registration_url %>
    </div>
  </div>
  <div class="field">
    <h3><%= f.label :categories %></h3>
    <%= f.select :category_ids,
      options_from_collection_for_select(@categories, 'id', 'name', @event.category_ids + [@category.id]), 
      {},
      :multiple => 'multiple' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/by_day.html.erb
<h1>Events for <%= @date.to_formatted_s :long %></h1>

<% if @events.empty? %>
  There are no events for this date.
<% else %>
  <ul>
    <% @events.each do |event| %>
      <li>
        <%= render :partial => 'event', :locals => { :event => event } %>
        <hr />
      </li>
    <% end %>
  </ul>
<% end %>

app/views/events/create.html.erb
Thank you for submitting your event. Once the Seeking Michigan staff approve it, it will show up on the <a href="http://seekingmichigan.org">Seeking Michigan site</a>.

app/views/events/edit.html.erb
<h2>Editing event</h2>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', category_events_path(@category) %>

app/views/events/index.html.erb
<h2>Listing events</h2>

<% if @events.empty? %>
  There are no events yet.
<% else %>
  <table style="width: 100%;">
    <tr>
      <th>Name</th>
      <th>Start</th>
      <th>End</th>
      <th>Location</th>
      <th>Email</th>
      <% if user_signed_in? %>
        <th></th>
        <th></th>
        <th></th>
      <% end %>
    </tr>

  <% @events.each do |event| %>
    <tr>
      <td><%= link_to event.name, event %></td>
      <td><%= event_date event.start %></td>
      <td><%= event_date event.end %></td>
      <td><%= event.location %></td>
      <td><%= mail_to event.email, event.email %></td>
      <% if user_signed_in? %>
        <td>
          <% if event.approved %>
            <%= link_to 'Unapprove', unapprove_event_path(event), :method => :put %>
          <% else %>
            <%= link_to 'Approve', approve_event_path(event), :method => :put %>
          <% end %>
        </td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %></td>
      <% end %>
    </tr>
  <% end %>
  </table>
<% end %>
<!-- Commented out "Add Event" link in Ruby code -->
<p><%= # link_to 'Add event', new_category_event_path(@category) %></p>

app/views/events/new.html.erb
<h2>Create a new event</h2>

<%= render 'form' %>

app/views/events/show.html.erb
<%= render :partial => 'event', :locals => { :event => @event } %>